### PR TITLE
Adding a IfCompilesTest file to new_branch

### PR DESCRIPTION
**Pull request by Mberic**

### CODE REVIEW

**Comment by yadavan88** [comment]
Hi @Mberic 
When I was doing the routine check on the Jenkins builds, I noticed this PR is failing. Could you please run `sbt scalafmtAll` to format the code and then push it.  That should solve this issue.

**Comment by Mberic** [comment]
hello, I've done so and committed the edited file again but it has still failed the checks

**Comment by yadavan88** [comment]
Hi @Mberic 
The format error is gone. Now it is due to the test failure.

[```
info] com.baeldung.scala.scalatest.IfCompilesTest *** ABORTED ***
[info]   Expected a compiler error, but got none for code: val x: Int = 258 (IfCompilesTest.scala:8)
```

Also, could you delete the `.scala-build` dir from the PR. That should not be committed

**Comment by Mberic** [comment]
Thanks a lot for the help. :+1:

**Pull request merged**
