### PR TITLE
Upgraded Most Libraries to latest version

### PR DESCRIPTION
**Pull request by yadavan88**
## Changes
- Upgraded scalatest to latest version
- Added all the related dependncies since scalatest changed their library structures
- Upgraded all possible libraries to latest version where there are no conflicts or api changes
- Fixed all imports due to re-structuring of scalatest modules
- Also, created a single deps list for scalatest to be used across all sub modules to avoid future issues like this. It is better to always use same scalatest version across all submodules.

**Note: Updated almost all libraries to latest version where there is no code change is required. Some of the pending libraries which cause compilation errors are akka, fs2, skunk, embedded-mongo, logback**

### CODE REVIEW

**Comment by yadavan88** [comment]
retest this please

**Comment by yadavan88** [comment]
retest this please

**Comment by lor6** [comment]
retest this please

**Comment by yadavan88** [comment]
@lor6 The pipeline passed here. Is this okay to merge or do you have any concerns about this? 
Once it is merged, I can sync other branches and start looking at breaking changes library updates.

**Comment by lor6** [comment]
Done @yadavan88 Was just waiting for the build to pass; I think there's an unstable test, unrelated to this change though.

**Pull request merged**
