### PR TITLE
Code for SCALA-350

### PR DESCRIPTION
**Pull request by hkateu**
Added code for SCALA-350, Refining existing types in Scala with Refined.

### CODE REVIEW

**Comment by yadavan88** [comment]
@hkateu 
Could you rebase your branch from the baeldung-master? Some validation has been added to the build recently. 
Thanks

**Comment by hkateu** [comment]
Hi @yadavan88, i performed a `rebase` and made the necessary changes.

**Comment by yadavan88** [comment]
Hi @hkateu 
Could you resolve this conflict? I had pushed another change before, and you can take the code from master while resolving conflict. Also, I think that this should have merged before. I will send a ping in the task. Thanks

**Comment by hkateu** [comment]
Sorry for the delay, I will work on this today

**Comment by yadavan88** [comment]
> @yadavan88 sorry for the delay, I will work on this today



> @yadavan88 sorry for the delay, I will work on this today

No problem. We are doing some refactoring and removing the warnings etc. You can take all changes from upstream for all files except yours. We are doing some refacortoring and removing warnings. This might go on for sometime, and just wanted to avoid causing problems for you again :D

**Comment by hkateu** [comment]
Hi @yadavan88, sorry for the delay, the checks have passed.

**Pull request merged**
